import type { CaseFile } from "../game/schema";

/** Hand-written case used by the offline demo provider and the tests. */
export const DEMO_CASE: CaseFile = {
  title: "The Last Train to Rijeka",
  setting: "A night sleeper from Zagreb to Rijeka, winter 1936",
  art_style: "Moody 1930s gouache illustration, warm lamplight against cold blue night, soft grain",
  briefing:
    "The overnight express has stopped in the snow outside Delnice. In compartment 3, shipping magnate Viktor Horvat is dead in his armchair, a glass of brandy still on the table.\n\nThe line is blocked until morning. Four passengers had business with Horvat tonight, and one of them killed him. You have until the snowplough arrives.",
  cover_prompt:
    "A 1930s sleeper train halted in deep snow at night, a single lit compartment window, steam curling under a lamp, pine forest behind.",
  victim: {
    name: "Viktor Horvat",
    description: "Owner of the Adria shipping line, 58, famous for his charm and for cutting corners.",
    cause_of_death: "Cyanide poisoning",
    found: "Found at 00:20 in compartment 3 by the conductor, Tomo Babić, answering a bell that had rung at midnight.",
  },
  suspects: [
    {
      id: "s1",
      name: "Ana Kovač",
      role: "Horvat's private secretary",
      appearance: "Neat grey suit, ink-stained fingers, eyes that never stop checking the door.",
      personality: "Precise, guarded, quietly ambitious",
      speech_style: "Clipped, formal sentences; answers questions with questions when cornered",
      relationship_to_victim: "Worked for him for nine years; he never let her forget it",
      opening_statement:
        "Detective. Mr Horvat was a demanding man, but he did not deserve this. I was in my compartment all evening, typing his correspondence. Ask me anything you need.",
      statements: [
        {
          id: "s1_a",
          text: "I stayed in my compartment all evening, typing Mr Horvat's letters. I never left it.",
          lie: true,
          contradicted_by: ["c4"],
          admission:
            "Very well. I was in the dining car from a quarter past eleven, meeting a man from Lloyd Triestino. I'm leaving Horvat's employ. And from that window, at a quarter to twelve, I saw Dr Marić walking back from compartment 3 with his black bag.",
        },
        {
          id: "s1_b",
          text: "Mr Horvat drank one glass of Pelinkovac at midnight, every night, without fail.",
          lie: false,
          contradicted_by: [],
          admission: "",
        },
      ],
      true_whereabouts: "Dining car from 23:15 to 23:50, meeting an agent of the rival Lloyd Triestino line.",
      secret: "She has accepted a job with Horvat's rival and was handing over his shipping contracts.",
      knowledge: [
        "At about 23:45, from the dining car window, she saw Dr Marić walking back along the corridor from the direction of compartment 3, carrying his black bag.",
        "Horvat kept a decanter of Pelinkovac brandy in his compartment and drank a glass every night at midnight, without fail.",
      ],
      portrait_prompt: "A composed woman in her thirties with a severe bob and a grey suit, a pencil behind her ear.",
    },
    {
      id: "s2",
      name: "Dr Leo Marić",
      role: "Physician and amateur lepidopterist",
      appearance: "Tall, stooped, round spectacles, a butterfly pin in his lapel.",
      personality: "Gentle, courteous, deeply controlled",
      speech_style: "Soft, measured, a little old-fashioned; fond of Latin names",
      relationship_to_victim: "Says they met tonight for the first time",
      opening_statement:
        "A terrible business. I examined him when the conductor called me, but there was nothing to be done. I had retired early with a book; I heard nothing until the commotion.",
      statements: [
        {
          id: "s2_a",
          text: "I had never met Mr Horvat before tonight. His name meant nothing to me.",
          lie: true,
          contradicted_by: ["c2", "c8"],
          admission: "Ivan Marić was my brother. He drowned on the Adria Star. Yes, I knew exactly who Viktor Horvat was.",
        },
        {
          id: "s2_b",
          text: "I retired at eleven and did not leave my compartment until the alarm.",
          lie: true,
          contradicted_by: ["c7", "s1_a_truth", "s4_a_truth"],
          admission: "I went to see him at twenty to twelve. I told him I was a doctor and offered to check his heart.",
        },
        {
          id: "s2_c",
          text: "I carry no poisons. I am a physician, not a chemist.",
          lie: true,
          contradicted_by: ["c3"],
          admission: "The killing jar. The cyanide is gone because I put it in his brandy while he looked for his papers.",
        },
      ],
      true_whereabouts: "Visited Horvat at 23:40 claiming to check his heart, and poisoned the brandy decanter while Horvat looked for his papers.",
      secret: "His younger brother Ivan drowned in 1934 when Horvat's unseaworthy ship Adria Star sank.",
      knowledge: ["He noticed Mira Horvat's glove was missing when she came to the scene."],
      portrait_prompt: "A tall thin man in his fifties with round spectacles, a tweed coat and a small silver butterfly pin.",
    },
    {
      id: "s3",
      name: "Mira Horvat",
      role: "The victim's young wife",
      appearance: "Fur stole, red lipstick, a restless hand turning her wedding ring.",
      personality: "Brittle, dramatic, frightened underneath",
      speech_style: "Emotional, rapid, drifts into complaints about Viktor",
      relationship_to_victim: "Married two years; unhappy",
      opening_statement:
        "You think I did it, don't you? Everyone will. Viktor and I argued, yes, but I was reading in the ladies' lounge. I never went near his compartment tonight.",
      statements: [
        {
          id: "s3_a",
          text: "I was reading in the ladies' lounge from eleven. I never went near Viktor's compartment.",
          lie: true,
          contradicted_by: ["c6"],
          admission: "Fine! I was in the corridor on my way to meet Tomo. Viktor was alive, I heard him humming behind the door at five to twelve.",
        },
        {
          id: "s3_b",
          text: "The conductor? I barely know the man.",
          lie: true,
          contradicted_by: ["s4_a_truth"],
          admission: "Tomo and I... it has been going on for a year. He's the only kind thing on this line.",
        },
      ],
      true_whereabouts: "In the corridor near compartment 3 at 23:55, slipping away to meet the conductor Tomo in the luggage van.",
      secret: "She is having an affair with the conductor, Tomo Babić.",
      knowledge: ["When she passed compartment 3 at about 23:55 the door was closed and she heard Viktor humming, so he was alive then."],
      portrait_prompt: "A glamorous young woman in a fur stole with finger-waved hair and anxious eyes.",
    },
    {
      id: "s4",
      name: "Tomo Babić",
      role: "Sleeping-car conductor",
      appearance: "Brass buttons, a moustache, smells faintly of tobacco.",
      personality: "Jovial, evasive, loyal to Mira",
      speech_style: "Folksy, lots of 'sir', avoids direct answers",
      relationship_to_victim: "Served him on this route for years; Horvat tipped badly",
      opening_statement:
        "Terrible night, sir. The bell from compartment 3 rang at midnight, but I was busy at the back and got there late, at twenty past. He was already gone, God rest him.",
      statements: [
        {
          id: "s4_a",
          text: "I was checking tickets in the rear carriages until the bell rang at midnight.",
          lie: true,
          contradicted_by: ["c5", "s3_a_truth"],
          admission: "All right, sir. I was in the luggage van, with my cigarettes, and with Mrs Horvat. But before that, at twenty to twelve, I saw the doctor knocking at compartment 3.",
        },
        {
          id: "s4_b",
          text: "Nobody went near compartment 3 before midnight, sir. I'd have seen them.",
          lie: true,
          contradicted_by: ["s1_a_truth"],
          admission: "The doctor. Dr Marić went in at about twenty to twelve. I didn't want trouble with a gentleman.",
        },
      ],
      true_whereabouts: "In the luggage van with Mira Horvat from 23:55 to 00:15.",
      secret: "He smuggles cigarettes across the border in the luggage van, and he is Mira's lover.",
      knowledge: ["The only passenger he saw near compartment 3 before midnight was Dr Marić, at about 23:40."],
      portrait_prompt: "A stocky railway conductor with a waxed moustache and a peaked cap with brass badge.",
    },
  ],
  locations: [
    { id: "loc_compartment", name: "Compartment 3", description: "Velvet seats, a lamp still burning, the smell of brandy and something bitter underneath." },
    { id: "loc_corridor", name: "Sleeping-car corridor", description: "A narrow carpeted corridor, frost on the windows, doors ticking with the cold." },
    { id: "loc_dining", name: "Dining car", description: "White tablecloths, abandoned coffee cups, a waiter asleep on a stool." },
    { id: "loc_doctor", name: "Compartment 7", description: "Tidy to the point of severity. Books on moths, a black medical bag, a wooden specimen case." },
    { id: "loc_luggage", name: "Luggage van", description: "Cold and dark, trunks strapped to the walls, a lantern hanging from a hook." },
  ],
  clues: [
    {
      id: "c1",
      title: "Brandy decanter",
      description: "A crystal decanter of Pelinkovac, half full. The neck smells faintly of bitter almonds. Only one glass has been used.",
      location_id: "loc_compartment",
      points_to: "none",
      significance: "The poison was in the decanter, not the glass: someone doctored it in advance, knowing Horvat drank at midnight.",
      red_herring: false,
    },
    {
      id: "c2",
      title: "Newspaper clipping",
      description: "A 1934 clipping on the sinking of the Adria Star, folded into Horvat's wallet. A list of the drowned is underlined, including 'Ivan Marić, 31'.",
      location_id: "loc_compartment",
      points_to: "s2",
      significance: "Links Dr Marić to Horvat: his brother died on Horvat's ship. Motive.",
      red_herring: false,
    },
    {
      id: "c7",
      title: "Specimen pin",
      description: "A long black insect pin with a tiny round head, caught in the carpet beside the table with the decanter.",
      location_id: "loc_compartment",
      points_to: "s2",
      significance: "Lepidopterist's pin: Dr Marić was at the decanter, contradicting his claim he never met Horvat or left his room.",
      red_herring: false,
    },
    {
      id: "c6",
      title: "Lady's glove",
      description: "A small kid-leather glove, scented with French perfume, lying against the door of compartment 3.",
      location_id: "loc_corridor",
      points_to: "s3",
      significance: "Mira was near the compartment, but on her way to meet Tomo; Horvat was alive then.",
      red_herring: true,
    },
    {
      id: "c4",
      title: "Dining car bill",
      description: "A bill for two coffees at 23:30, signed 'A. Kovač', with a business card of Lloyd Triestino tucked beneath it.",
      location_id: "loc_dining",
      points_to: "s1",
      significance: "Ana lied about her alibi, but only to hide her defection to a rival. It puts her in the dining car, from where she saw Dr Marić.",
      red_herring: true,
    },
    {
      id: "c3",
      title: "Killing jar",
      description: "A glass jar from the specimen case, of the kind collectors use to kill moths. Its base should hold pellets under plaster; the plaster has been dug out and it is empty.",
      location_id: "loc_doctor",
      points_to: "s2",
      significance: "Killing jars hold potassium cyanide. The missing pellets are the poison. Means.",
      red_herring: false,
    },
    {
      id: "c5",
      title: "Cigarette crate",
      description: "A crate marked 'Machine parts' holding two hundred packets of foreign cigarettes, sealed with the conductor's personal wax seal.",
      location_id: "loc_luggage",
      points_to: "s4",
      significance: "Tomo is a smuggler, which is why he lies about where he was. Not the murder.",
      red_herring: true,
    },
    {
      id: "c8",
      title: "Telegram for Horvat",
      description: "From the Rijeka harbour master: 'Adria Star inquiry reopened. Brother of drowned officer Marić travelling on your train. Take care.'",
      location_id: "loc_luggage",
      points_to: "s2",
      significance: "Horvat was warned that Marić's brother was aboard: the doctor's claim never to have heard of him is a lie.",
      red_herring: false,
    },
  ],
  events: [
    {
      at_hour: 6,
      title: "A telegram arrives",
      text: "The stationmaster's boy wades through the snow with a telegram for Mr Horvat. It's in the luggage van now.",
      effect: "reveal_clue",
      target: "c8",
    },
    {
      at_hour: 14,
      title: "Footprints in the snow",
      text: "Someone hauled a heavy crate out of the luggage van and buried it in a drift. Whatever it was, it's gone.",
      effect: "destroy_clue",
      target: "c5",
    },
    {
      at_hour: 26,
      title: "A lawyer by sledge",
      text: "Mrs Horvat's lawyer has arrived from Delnice. She will answer no more questions.",
      effect: "silence",
      target: "s3",
    },
  ],
  solution: {
    culprit_id: "s2",
    motive: "Revenge: Horvat knowingly sent the unseaworthy Adria Star to sea, and Dr Marić's brother Ivan drowned when it sank.",
    method: "Cyanide from the killing jar in his specimen case, dropped into Horvat's brandy decanter during a pretended heart check at 23:40, knowing Horvat drank at midnight.",
    opportunity: "He visited compartment 3 at 23:40, seen by the conductor and the secretary, then returned to his room and waited.",
    key_clue_ids: ["c1", "c2", "c3", "c7"],
    explanation:
      "The brandy, not the glass, was poisoned, so the killer did not need to be there at midnight, only to know Horvat's habit and to reach the decanter earlier. Ana Kovač and Tomo Babić both saw Dr Marić at compartment 3 around 23:40, though each lied to hide their own secrets.\n\nThe doctor claimed never to have met Horvat, yet one of his specimen pins lay beside the decanter, his killing jar had been emptied of its cyanide, and Horvat carried a clipping of the Adria Star disaster with Ivan Marić's name underlined. A brother's revenge, prepared with a collector's patience.",
  },
  timeline: [
    { time: "22:00", event: "Horvat retires to compartment 3." },
    { time: "23:15", event: "Ana Kovač meets the Lloyd Triestino agent in the dining car." },
    { time: "23:40", event: "Dr Marić visits Horvat and poisons the decanter." },
    { time: "23:45", event: "Ana sees Dr Marić returning along the corridor with his bag." },
    { time: "23:55", event: "Mira passes compartment 3, drops her glove; Horvat is humming." },
    { time: "00:00", event: "Horvat pours his midnight brandy and rings the bell as the poison takes hold." },
    { time: "00:20", event: "Tomo finds the body." },
  ],
};
