import type { CaseFile } from "../game/schema";

/** Hand-written case used by the offline demo provider and the tests. */
export const DEMO_CASE: CaseFile = {
  title: "The Last Train to Rijeka",
  setting: "A night sleeper from Zagreb to Rijeka, winter 1936",
  art_style: "Moody 1930s gouache illustration, warm lamplight against cold blue night, soft grain",
  briefing:
    "The overnight express has stopped in the snow outside Delnice. In compartment 3, shipping magnate Viktor Horvat is dead in his armchair, a glass of brandy still on the table.\n\nThe line is blocked until morning. Four passengers had business with Horvat tonight, and one of them killed him. You have until the snowplough arrives.",
  cover_prompt:
    "A 1930s sleeper train halted in deep snow at night, a single lit compartment window, steam curling under a lamp, pine forest behind.",
  victim: {
    name: "Viktor Horvat",
    description: "Owner of the Adria shipping line, 58, famous for his charm and for cutting corners.",
    cause_of_death: "Cyanide poisoning",
    found: "Found at 00:20 in compartment 3 by the conductor, Tomo Babić, answering a bell that had rung at midnight.",
  },
  suspects: [
    {
      id: "s1",
      name: "Ana Kovač",
      role: "Horvat's private secretary",
      appearance: "Neat grey suit, ink-stained fingers, eyes that never stop checking the door.",
      personality: "Precise, guarded, quietly ambitious",
      speech_style: "Clipped, formal sentences; answers questions with questions when cornered",
      relationship_to_victim: "Worked for him for nine years; he never let her forget it",
      opening_statement:
        "Detective. Mr Horvat was a demanding man, but he did not deserve this. I was in my compartment all evening, typing his correspondence. Ask me anything you need.",
      claimed_alibi: "Typing letters alone in compartment 5 from 22:00 until the alarm.",
      true_whereabouts: "Dining car from 23:15 to 23:50, meeting an agent of the rival Lloyd Triestino line.",
      secret: "She has accepted a job with Horvat's rival and was handing over his shipping contracts.",
      lies: ["She never left her compartment.", "She has never met anyone from Lloyd Triestino."],
      knowledge: [
        "At about 23:45, from the dining car window, she saw Dr Marić walking back along the corridor from the direction of compartment 3, carrying his black bag.",
        "Horvat kept a decanter of Pelinkovac brandy in his compartment and drank a glass every night at midnight, without fail.",
      ],
      breaking_point: "Shown the dining car bill (c4), she admits the meeting and then, to clear herself, reveals she saw Dr Marić near compartment 3 at 23:45.",
      portrait_prompt: "A composed woman in her thirties with a severe bob and a grey suit, a pencil behind her ear.",
    },
    {
      id: "s2",
      name: "Dr Leo Marić",
      role: "Physician and amateur lepidopterist",
      appearance: "Tall, stooped, round spectacles, a butterfly pin in his lapel.",
      personality: "Gentle, courteous, deeply controlled",
      speech_style: "Soft, measured, a little old-fashioned; fond of Latin names",
      relationship_to_victim: "Says they met tonight for the first time",
      opening_statement:
        "A terrible business. I examined him when the conductor called me, but there was nothing to be done. I had retired early with a book; I heard nothing until the commotion.",
      claimed_alibi: "Asleep in compartment 7 from 23:00.",
      true_whereabouts: "Visited Horvat at 23:40 claiming to check his heart, and poisoned the brandy decanter while Horvat looked for his papers.",
      secret: "His younger brother Ivan drowned in 1934 when Horvat's unseaworthy ship Adria Star sank.",
      lies: ["He had never met Horvat before tonight.", "He did not leave his compartment before the alarm.", "He has no poisons with him."],
      knowledge: ["He noticed Mira Horvat's glove was missing when she came to the scene."],
      breaking_point: "Confronted with the killing jar (c3) together with the Adria Star clipping (c2) or the specimen pin (c7), he stops lying and admits he killed Horvat for his brother.",
      portrait_prompt: "A tall thin man in his fifties with round spectacles, a tweed coat and a small silver butterfly pin.",
    },
    {
      id: "s3",
      name: "Mira Horvat",
      role: "The victim's young wife",
      appearance: "Fur stole, red lipstick, a restless hand turning her wedding ring.",
      personality: "Brittle, dramatic, frightened underneath",
      speech_style: "Emotional, rapid, drifts into complaints about Viktor",
      relationship_to_victim: "Married two years; unhappy",
      opening_statement:
        "You think I did it, don't you? Everyone will. Viktor and I argued, yes, but I was reading in the ladies' lounge. I never went near his compartment tonight.",
      claimed_alibi: "Reading in the ladies' lounge from 23:00.",
      true_whereabouts: "In the corridor near compartment 3 at 23:55, slipping away to meet the conductor Tomo in the luggage van.",
      secret: "She is having an affair with the conductor, Tomo Babić.",
      lies: ["She was in the ladies' lounge.", "She barely knows the conductor."],
      knowledge: ["When she passed compartment 3 at about 23:55 the door was closed and she heard Viktor humming, so he was alive then."],
      breaking_point: "Shown the glove from the corridor (c6), she admits she was near compartment 3 to meet Tomo, and that Viktor was alive and humming at 23:55.",
      portrait_prompt: "A glamorous young woman in a fur stole with finger-waved hair and anxious eyes.",
    },
    {
      id: "s4",
      name: "Tomo Babić",
      role: "Sleeping-car conductor",
      appearance: "Brass buttons, a moustache, smells faintly of tobacco.",
      personality: "Jovial, evasive, loyal to Mira",
      speech_style: "Folksy, lots of 'sir', avoids direct answers",
      relationship_to_victim: "Served him on this route for years; Horvat tipped badly",
      opening_statement:
        "Terrible night, sir. The bell from compartment 3 rang at midnight, but I was busy at the back and got there late, at twenty past. He was already gone, God rest him.",
      claimed_alibi: "Checking tickets in the rear carriages until the bell.",
      true_whereabouts: "In the luggage van with Mira Horvat from 23:55 to 00:15.",
      secret: "He smuggles cigarettes across the border in the luggage van, and he is Mira's lover.",
      lies: ["He was checking tickets.", "Nothing in the luggage van belongs to him."],
      knowledge: ["The only passenger he saw near compartment 3 before midnight was Dr Marić, at about 23:40."],
      breaking_point: "Shown the cigarette crate (c5), he admits the smuggling and that he was with Mira, and mentions seeing Dr Marić at compartment 3 at 23:40.",
      portrait_prompt: "A stocky railway conductor with a waxed moustache and a peaked cap with brass badge.",
    },
  ],
  locations: [
    { id: "loc_compartment", name: "Compartment 3", description: "Velvet seats, a lamp still burning, the smell of brandy and something bitter underneath." },
    { id: "loc_corridor", name: "Sleeping-car corridor", description: "A narrow carpeted corridor, frost on the windows, doors ticking with the cold." },
    { id: "loc_dining", name: "Dining car", description: "White tablecloths, abandoned coffee cups, a waiter asleep on a stool." },
    { id: "loc_doctor", name: "Compartment 7", description: "Tidy to the point of severity. Books on moths, a black medical bag, a wooden specimen case." },
    { id: "loc_luggage", name: "Luggage van", description: "Cold and dark, trunks strapped to the walls, a lantern hanging from a hook." },
  ],
  clues: [
    {
      id: "c1",
      title: "Brandy decanter",
      description: "A crystal decanter of Pelinkovac, half full. The neck smells faintly of bitter almonds. Only one glass has been used.",
      location_id: "loc_compartment",
      points_to: "none",
      significance: "The poison was in the decanter, not the glass: someone doctored it in advance, knowing Horvat drank at midnight.",
      red_herring: false,
    },
    {
      id: "c2",
      title: "Newspaper clipping",
      description: "A 1934 clipping on the sinking of the Adria Star, folded into Horvat's wallet. A list of the drowned is underlined, including 'Ivan Marić, 31'.",
      location_id: "loc_compartment",
      points_to: "s2",
      significance: "Links Dr Marić to Horvat: his brother died on Horvat's ship. Motive.",
      red_herring: false,
    },
    {
      id: "c7",
      title: "Specimen pin",
      description: "A long black insect pin with a tiny round head, caught in the carpet beside the table with the decanter.",
      location_id: "loc_compartment",
      points_to: "s2",
      significance: "Lepidopterist's pin: Dr Marić was at the decanter, contradicting his claim he never met Horvat or left his room.",
      red_herring: false,
    },
    {
      id: "c6",
      title: "Lady's glove",
      description: "A small kid-leather glove, scented with French perfume, lying against the door of compartment 3.",
      location_id: "loc_corridor",
      points_to: "s3",
      significance: "Mira was near the compartment, but on her way to meet Tomo; Horvat was alive then.",
      red_herring: true,
    },
    {
      id: "c4",
      title: "Dining car bill",
      description: "A bill for two coffees at 23:30, signed 'A. Kovač', with a business card of Lloyd Triestino tucked beneath it.",
      location_id: "loc_dining",
      points_to: "s1",
      significance: "Ana lied about her alibi, but only to hide her defection to a rival. It puts her in the dining car, from where she saw Dr Marić.",
      red_herring: true,
    },
    {
      id: "c3",
      title: "Killing jar",
      description: "A glass jar from the specimen case, of the kind collectors use to kill moths. Its base should hold pellets under plaster; the plaster has been dug out and it is empty.",
      location_id: "loc_doctor",
      points_to: "s2",
      significance: "Killing jars hold potassium cyanide. The missing pellets are the poison. Means.",
      red_herring: false,
    },
    {
      id: "c5",
      title: "Cigarette crate",
      description: "A crate marked 'Machine parts' holding two hundred packets of foreign cigarettes, sealed with the conductor's personal wax seal.",
      location_id: "loc_luggage",
      points_to: "s4",
      significance: "Tomo is a smuggler, which is why he lies about where he was. Not the murder.",
      red_herring: true,
    },
  ],
  solution: {
    culprit_id: "s2",
    motive: "Revenge: Horvat knowingly sent the unseaworthy Adria Star to sea, and Dr Marić's brother Ivan drowned when it sank.",
    method: "Cyanide from the killing jar in his specimen case, dropped into Horvat's brandy decanter during a pretended heart check at 23:40, knowing Horvat drank at midnight.",
    opportunity: "He visited compartment 3 at 23:40, seen by the conductor and the secretary, then returned to his room and waited.",
    key_clue_ids: ["c1", "c2", "c3", "c7"],
    explanation:
      "The brandy, not the glass, was poisoned, so the killer did not need to be there at midnight, only to know Horvat's habit and to reach the decanter earlier. Ana Kovač and Tomo Babić both saw Dr Marić at compartment 3 around 23:40, though each lied to hide their own secrets.\n\nThe doctor claimed never to have met Horvat, yet one of his specimen pins lay beside the decanter, his killing jar had been emptied of its cyanide, and Horvat carried a clipping of the Adria Star disaster with Ivan Marić's name underlined. A brother's revenge, prepared with a collector's patience.",
  },
  timeline: [
    { time: "22:00", event: "Horvat retires to compartment 3." },
    { time: "23:15", event: "Ana Kovač meets the Lloyd Triestino agent in the dining car." },
    { time: "23:40", event: "Dr Marić visits Horvat and poisons the decanter." },
    { time: "23:45", event: "Ana sees Dr Marić returning along the corridor with his bag." },
    { time: "23:55", event: "Mira passes compartment 3, drops her glove; Horvat is humming." },
    { time: "00:00", event: "Horvat pours his midnight brandy and rings the bell as the poison takes hold." },
    { time: "00:20", event: "Tomo finds the body." },
  ],
};
